/**
 * Telemetry message type definitions for connector-to-dashboard communication
 * @packageDocumentation
 * @remarks
 * These types match the dashboard telemetry server expectations (Story 3.3).
 * All telemetry messages include nodeId for multi-connector differentiation.
 */

import { RoutingTableEntry } from '@agent-runtime/shared';

/**
 * Telemetry message types supported by dashboard server
 */
export type TelemetryMessageType =
  | 'NODE_STATUS'
  | 'PACKET_RECEIVED'
  | 'PACKET_SENT'
  | 'ROUTE_LOOKUP'
  | 'LOG';

/**
 * Base telemetry message structure
 * @remarks
 * All telemetry messages sent from connector to dashboard follow this format.
 * The data field contains type-specific payload.
 */
export interface TelemetryMessage {
  /** Message type discriminator */
  type: TelemetryMessageType;
  /** Connector node ID (e.g., "connector-a") */
  nodeId: string;
  /** ISO 8601 timestamp (e.g., "2025-12-29T10:00:00.000Z") */
  timestamp: string;
  /** Event-specific payload */
  data: NodeStatusData | PacketReceivedData | PacketSentData | RouteLookupData | LogTelemetryData;
}

/**
 * Peer status information for telemetry
 */
export interface PeerStatus {
  /** Unique peer identifier */
  id: string;
  /** WebSocket URL for BTP connection */
  url: string;
  /** Current connection state */
  connected: boolean;
}

/**
 * NODE_STATUS telemetry data
 * @remarks
 * Sent on connector startup and periodically for health monitoring.
 * Provides dashboard with connector state, routing table, and peer connections.
 */
export interface NodeStatusData {
  /** Current routing table entries */
  routes: RoutingTableEntry[];
  /** Connected peers with status */
  peers: PeerStatus[];
  /** Health status: healthy, unhealthy, or starting */
  health: 'healthy' | 'unhealthy' | 'starting';
  /** Connector uptime in seconds */
  uptime: number;
  /** Number of currently connected peers */
  peersConnected: number;
  /** Total number of configured peers */
  totalPeers: number;
}

/**
 * PACKET_RECEIVED telemetry data
 * @remarks
 * Emitted when ILP packet arrives at connector via BTP.
 * Enables packet flow visualization in dashboard.
 */
export interface PacketReceivedData {
  /** Unique packet identifier (executionCondition hex string) */
  packetId: string;
  /** ILP packet type */
  packetType: 'PREPARE' | 'FULFILL' | 'REJECT';
  /** Source connector or peer (may be "unknown") */
  source: string;
  /** ILP destination address */
  destination: string;
  /** Transfer amount as string (bigint serialization) */
  amount: string;
}

/**
 * PACKET_SENT telemetry data
 * @remarks
 * Emitted when connector forwards packet to next hop via BTP.
 * Completes packet flow visualization in dashboard.
 */
export interface PacketSentData {
  /** Unique packet identifier (matches PACKET_RECEIVED packetId) */
  packetId: string;
  /** Next hop peer identifier */
  nextHop: string;
  /** ISO 8601 timestamp of send event */
  timestamp: string;
}

/**
 * ROUTE_LOOKUP telemetry data
 * @remarks
 * Emitted after routing table lookup during packet processing.
 * Shows routing decision logic in dashboard.
 */
export interface RouteLookupData {
  /** ILP destination address from packet */
  destination: string;
  /** Selected next hop peer (null if no route found) */
  selectedPeer: string | null;
  /** Routing decision reason (e.g., "longest prefix match", "no route found") */
  reason: string;
}

/**
 * LOG telemetry data
 * @remarks
 * Emitted for every log entry generated by the connector.
 * Enables centralized log viewing and filtering in dashboard.
 */
export interface LogTelemetryData {
  /** Log level (debug, info, warn, error) */
  level: 'debug' | 'info' | 'warn' | 'error';
  /** ISO 8601 timestamp of log entry */
  timestamp: string;
  /** Connector node ID that emitted this log */
  nodeId: string;
  /** Human-readable log message */
  message: string;
  /** Optional packet correlation ID for tracking */
  correlationId?: string;
  /** Additional structured context fields */
  context?: Record<string, unknown>;
}
