# Production 3-Node Mesh Topology: Node 2
# Topology: Each connector connected to all others
#
# This is production-node-2 in a full mesh topology with 3 nodes.
# In a mesh topology, each connector has direct connections to all other connectors,
# providing redundant paths and low latency routing.
#
# Production Features:
# - INFO-level structured JSON logging
# - Secrets loaded from environment variables
# - Health check endpoint enabled
# - Production-ready configuration
#
# Network Flow:
# - Direct routes to Node 1 and Node 3
# - No intermediate hops required

# Node Identity
nodeId: production-node-2
btpServerPort: 3001
logLevel: info

# Optional Configuration
healthCheckPort: 8080

# Peer Connections
# Node 2 connects to all other nodes in the mesh
peers:
  - id: production-node-1
    url: ws://production-node-1:3000
    authToken: prod-secret-1-to-2

  - id: production-node-3
    url: ws://production-node-3:3002
    authToken: prod-secret-2-to-3

# Routing Table
# Direct routes to each peer connector
routes:
  - prefix: g.production.node1
    nextHop: production-node-1
    priority: 0

  - prefix: g.production.node2
    nextHop: production-node-2
    priority: 0

  - prefix: g.production.node3
    nextHop: production-node-3
    priority: 0
